require 'openssl'
NameError: uninitialized constant Fastly::Client::OpenSSL
	from /Users/thomas/.chefdk/gem/ruby/2.1.0/gems/fastly-1.2.2/lib/fastly/client.rb:21:in `initialize'
	from /Users/thomas/.chefdk/gem/ruby/2.1.0/gems/fastly-1.2.2/lib/fastly/fetcher.rb:19:in `new'
	from /Users/thomas/.chefdk/gem/ruby/2.1.0/gems/fastly-1.2.2/lib/fastly/fetcher.rb:19:in `client'
	from /Users/thomas/.chefdk/gem/ruby/2.1.0/gems/fastly-1.2.2/lib/fastly.rb:48:in `initialize'
	from (irb):3:in `new'
	from (irb):3
	from /opt/chefdk/embedded/bin/irb:11:in `<main>'